version: 1.0.{build}
os: Visual Studio 2015
test: off
clone_folder: C:\projects\nanogui
branches:
  only:
    - master
install:
  - git submodule update --init --recursive
  - cinstall: python
build_script:
  - echo Running cmake...
  - cd c:\projects\nanogui
  - cmake -G "Visual Studio 14 2015 Win64" -DPYTHON_EXECUTABLE:FILEPATH=C:/Python34-x64/python.exe .
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=Release /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% nanogui.sln
